# Azure config
azure_vm_user: azureuser
resource_group_name: gw-gks-icap-squid-proxy
vm_name: Squid-VM0
location: eastus
ssh_key:
  - path: /home/azureuser/.ssh/authorized_keys
    key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDWQ0tRH535reDGXnhzkMPK8duSdZTX0R11sIJ7osHrHzx7+em28+wW1gGtLeRESPsmG3xuG/LV5MBDRDWVtyRCnDuQX+6qmWnVZLtAl0PuxJ3IpC89TPDRqtJ+uGAm1JtHKOfT0WC9/z9+EhN9NQJtFeCtDKfDD5pf2ZlVRoDk1Le74EaoVlYbQASvOMzALFNvjtiKFh4ssKozN0bdgPMI7cnKYlF0aGWryGBlO9X0IEMQc2DHkfhkgjPtPWJ2V6NbwyFYw7nVAW26eghuxhP5hcQSkZW8ESl+J+jZlWdQnHqfnIBb53i02yLEEHAGF1sbk5IbLT9mlSSWKfJ49y75C+JcaCN/ns6udZRr2wYkP0XJtCTsf7yyaaBdOh4LWIXMMNIIy10sSyILWhJLIe8zQFE4LDBviO/kz6MAXUDh2spMGKI7b5I4SU7zQNghX6v4lf5NCNPqcuxSu335TKaVpm5ToPq1DpCvHsCosTOtwbxOffD6cEmA5Zd9ogkg/d0="
hostname: "{{ vm_name }}"
# Squid config
icap_url: icap://51.137.28.90:1344/gw_rebuild # Use IP and Port (do not use domain)
squid_port: 3128
squid_transparent_http_port: 3129
squid_transparent_https_port: 3130
protected_domains:
  - app.gohire.io
  - filedrop.glasswallsolutions.com
  - gw-demo-sample-files-eu1.s3-eu-west-1.amazonaws.com
